import type { MaybePromise } from "../../promises/types.js";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type IndexedDatabase from "./index.js";

/**
 * The definition of an index of an object store of an {@link IndexedDatabase}.
 *
 * ---
 *
 * @example
 * ```ts
 * const byName: IndexDefinition = { name: "byName", keyPath: "name", unique: false };
 * ```
 */
export interface IndexDefinition
{
    /**
     * The name of the index.
     */
    readonly name: string;

    /**
     * The key path (or paths) of the records the index is built on.
     */
    readonly keyPath: string | string[];

    /**
     * Whether the index enforces unique values. Default is `false`.
     */
    readonly unique?: boolean;

    /**
     * Whether the index adds an entry for each element of an array key path. Default is `false`.
     */
    readonly multiEntry?: boolean;
}

/**
 * The function that migrates the records of an object store using in-line keys (a `keyPath`)
 * while the database is being upgraded. See {@link InlineStoreDefinition.migrate}.
 *
 * It's invoked on every record, on every upgrade, and returns the record to store:
 * the same reference leaves it untouched, a new value rewrites it and `undefined` deletes it.
 *
 * ---
 *
 * @example
 * ```ts
 * const migrate: InlineMigrationHandler = (record, key, oldVersion) =>
 * {
 *     if (oldVersion >= 2) { return record; }
 *
 *     return { ...(record as SaveRecordV1), difficulty: "normal" };
 * };
 * ```
 *
 * ---
 *
 * @param record The existing record.
 * @param key The key of the existing record.
 * @param oldVersion The version the database is upgrading from.
 *
 * @returns The record to store, or `undefined` to delete it.
 */
export type InlineMigrationHandler = (record: unknown, key: IDBValidKey, oldVersion: number) => unknown;

/**
 * The function that migrates the records of an object store using out-of-line keys (no `keyPath`)
 * while the database is being upgraded. See {@link OutOfLineStoreDefinition.migrate}.
 *
 * It's invoked on every record, on every upgrade, and returns a `[key, value]` tuple:
 * the same key and value reference leaves the record untouched, a different key or value rewrites it
 * (an `undefined` key delegates it to the store's generator) and `undefined` deletes it.
 *
 * ---
 *
 * @example
 * ```ts
 * const migrate: OutOfLineMigrationHandler = (record, key, oldVersion) =>
 * {
 *     if (oldVersion >= 2) { return [key, record]; }
 *
 *     return [`note:${String(key)}`, record];
 * };
 * ```
 *
 * ---
 *
 * @param record The existing record.
 * @param key The key of the existing record.
 * @param oldVersion The version the database is upgrading from.
 *
 * @returns The `[key, value]` tuple to store, or `undefined` to delete the record.
 */
export type OutOfLineMigrationHandler = (record: unknown, key: IDBValidKey, oldVersion: number) =>
    [IDBValidKey | undefined, unknown] | undefined;

interface BaseStoreDefinition<K extends string>
{
    /**
     * The name of the object store.
     */
    readonly name: K;

    /**
     * Whether the store generates its own keys. Default is `false`.
     */
    readonly autoIncrement?: boolean;

    /**
     * The indexes the store must have.
     */
    readonly indexes?: readonly IndexDefinition[];
}

/**
 * The definition of an object store of an {@link IndexedDatabase} using in-line keys:
 * the key of each record is extracted from the record itself through the `keyPath`.
 *
 * ---
 *
 * @example
 * ```ts
 * const saves: InlineStoreDefinition = { name: "saves", keyPath: "slot" };
 * ```
 *
 * ---
 *
 * @template K The type of the store name.
 */
export interface InlineStoreDefinition<K extends string = string> extends BaseStoreDefinition<K>
{
    /**
     * The key path (or paths) used to extract the key from each record.
     */
    readonly keyPath: string | string[];

    /**
     * Migrates the records of the store while the database is being upgraded.
     * See {@link InlineMigrationHandler} for the details.
     *
     * Also note that:
     * - Throwing, or returning a record that doesn't fit the key rules, aborts the whole upgrade.
     */
    readonly migrate?: InlineMigrationHandler;
}

/**
 * The definition of an object store of an {@link IndexedDatabase} using out-of-line keys:
 * the key of each record is provided explicitly when writing, or generated by the store.
 *
 * ---
 *
 * @example
 * ```ts
 * const logs: OutOfLineStoreDefinition = { name: "logs", autoIncrement: true };
 * const notes: OutOfLineStoreDefinition = { name: "notes" };
 * ```
 *
 * ---
 *
 * @template K The type of the store name.
 */
export interface OutOfLineStoreDefinition<K extends string = string> extends BaseStoreDefinition<K>
{
    /**
     * Out-of-line stores have no key path. It can be omitted or set to `null`.
     */
    readonly keyPath?: null;

    /**
     * Migrates the records of the store while the database is being upgraded.
     * See {@link OutOfLineMigrationHandler} for the details.
     *
     * Also note that:
     * - Throwing, or delegating the key to a store without `autoIncrement`, aborts the whole upgrade.
     */
    readonly migrate?: OutOfLineMigrationHandler;
}

/**
 * The definition of an object store of an {@link IndexedDatabase}: either an {@link InlineStoreDefinition}
 * or an {@link OutOfLineStoreDefinition}, depending on whether a `keyPath` is declared.
 *
 * The definitions passed to {@link IndexedDatabase.Open} describe the desired schema.
 * When the version increases, the existing schema is reconciled with them, store by store:
 * - A missing store is created, along with its indexes.
 * - A store whose `keyPath` or `autoIncrement` changed is recreated and its records are copied over,
 *   through its `migrate` function when provided.
 * - Otherwise, its indexes are created, recreated or deleted to match the declaration,
 *   and its records are migrated in place when it declares a `migrate` function.
 * - A store that exists but isn't declared is left untouched: stores are never deleted implicitly.
 *
 * ---
 *
 * @example
 * ```ts
 * const stores: StoreDefinition[] = [
 *     { name: "saves", keyPath: "slot", indexes: [{ name: "byName", keyPath: "name" }] },
 *     { name: "logs", autoIncrement: true }
 * ];
 * ```
 *
 * ---
 *
 * @template K The type of the store name.
 */
export type StoreDefinition<K extends string = string> = InlineStoreDefinition<K> | OutOfLineStoreDefinition<K>;

/**
 * The function invoked by {@link IndexedDatabase.Open} once the schema has been reconciled,
 * for whatever the store definitions can't express: deleting stores, moving records between them, seeding data.
 *
 * It may be asynchronous, but **only IndexedDB requests can be awaited** (see {@link IndexedDatabase.Request}):
 * awaiting anything else lets the `versionchange` transaction commit underneath.
 *
 * Also note that:
 * - Throwing, or returning a promise that rejects, aborts the whole upgrade.
 *
 * ---
 *
 * @example
 * ```ts
 * const onUpgrade: UpgradeHandler = async (database, oldVersion, newVersion, transaction) =>
 * {
 *     if (oldVersion < 2) { database.deleteObjectStore("legacy"); }
 *     if (oldVersion === 0)
 *     {
 *         const settings = transaction.objectStore("settings");
 *
 *         await IndexedDatabase.Request(settings.add({ key: "volume", value: 0.5 }));
 *     }
 * };
 * ```
 *
 * ---
 *
 * @param database The database being upgraded.
 * @param oldVersion The version the database is upgrading from (`0` for a new database).
 * @param newVersion The version the database is upgrading to.
 * @param transaction The `versionchange` transaction the upgrade runs in.
 */
export type UpgradeHandler = (
    database: IDBDatabase, oldVersion: number, newVersion: number, transaction: IDBTransaction
) => MaybePromise<void>;
